### ISSUE TITLE
eslint-plugin-vue から学ぶ Vue.js の書き方

### ISSUE THREAD

**Issue by ubugeeei** [chibivue-land/articles-zenn-plaza#72]
### 概要

eslint-plugin-vue から学ぶ Vue.js の書き方

### 詳細

ルールの裏には需要がある。
なぜそんなルールが必要なのか、と言うことを eslint のルール一覧から逆引きする。
そして Vue.js の書き方のプラクティスについて学ぶ。

**Comment by 2nofa11** [comment]
勉強になりそうなので書いてみようと思います！

**Comment by ubugeeei** [comment]
https://zenn.dev/comm_vue_nuxt/articles/04834732d9ae3f
