### ISSUE TITLE
[追加希望]: Chaika

### ISSUE THREAD

**Issue by kanae-chaika** [chibivue-land/articles-zenn-plaza#79]
### Zenn User Name

Chaika

### GitHub

kanae-chaika

### 備考欄

よろしくお願いいたします。

**Comment by shinGangan** [comment]
@kanae-chaika 

Zenn Publicationに招待しました！
登録されているメールアドレスに招待メールが届いておりますのでご確認お願いします🙏

**Comment by shinGangan** [comment]
#### 運営コメント

Publicationへの追加を確認しました。本イシューをクローズします。
