### ISSUE TITLE
request: Vue Fes アフターイベントの参加レポートを書いてほしい

### ISSUE THREAD

**Issue by shinGangan** [chibivue-land/articles-zenn-plaza#81]
### 概要

After Partyの参加レポートを書いてほしい

### 詳細

Vue Fes Japan 2024開催の興奮は終わった現在でも続いている。今年は3つのAfter Eventsが開催される予定である。

- 10/29: [Vue Fes Japan 2024 After Talk](https://yappli.connpass.com/event/330660/)
- 10/30: [Vue Fes Japan 2024 After Night](https://studist.connpass.com/event/327702/)
- 11/01: [Vue Fes Japan 2024 After Meetup](https://medpeer.connpass.com/event/331417/)

このAfter Eventsの参加レポートを誰か書いてほしい。来年のAfter Eventsの参考になれば良いと考えています

### 備考欄

- 理想は1イベント1記事である。ただ最低1本でもあることが好ましいです
- 普段記事をあまり書いたことない、Vue Fes Japanで始めてVue.jsやイベントに参加した方に1本ずつ(3イベント × 3人)書いてほしい気持ちがあります。もちろん無理のない範囲で

### 🔗 Related Issue

- #84
  - author: @neginasu

**Comment by shinGangan** [comment]
### 運営コメント

執筆希望あれば @shinGangan をメンションしてください。アサインします。

**Comment by neginasu** [comment]
@shinGangan 
10/29の[Vue Fes Japan 2024 After Talk](https://yappli.connpass.com/event/330660/)に参加したのでこちらの記事を書いてみたいです！

**Comment by shinGangan** [comment]
@neginasu 

是非是非～！よろしくお願いします！
もしレビュー必要であれば下書き完了後(構成一緒に考えるでもOK)にメンションください🙏

**Comment by neginasu** [comment]
@shinGangan 
ありがとうございます！
書き終わり次第レビューお願いさせていただきます🙇🏻‍♀️

**Comment by kspace-trk** [comment]
@shinGangan `After Party`は、Vue Fes Japan当日のアフターパーティーを示す用語な気がするので、`関連イベント`や`アフターイベント`という表現がよさそうです！
ref: https://vuefes.jp/2024/events

**Comment by shinGangan** [comment]
@kspace-trk 

指摘ありがとうございます！🙏
他カンファレンスの動きを見る限りだとそこまで気にする必要はないかなと思っています。ただ、今回はアフターイベントが多いので、非公式のものを**アフターイベント**としておくほうが良さそうですね！

レビューの際に使います～！指摘感謝です

**Comment by shinGangan** [comment]
今後追加される可能性がないためクローズする。

---

@neginasu 、LGTMです🎉
執筆頂きありがとうございます！
