### ISSUE TITLE
request: Vue Fes Japanのアフターイベントに参加しました ~その1~

### ISSUE THREAD

**Issue by shinGangan** [chibivue-land/articles-zenn-plaza#84]
### Context

- #81 を子イシューに分割した。レビュー等々はこちらで実施する。
- イシュータイトルと記事タイトルは別物である

**Comment by shinGangan** [comment]
@neginasu 

他者スレッドが混ざることを避けるため、こっちにイシューを分割しました〜
レビュー、質問事項などはこっちのイシューに投げてもらえると良いです🙆

**Comment by neginasu** [comment]
@shinGangan 
承知しました🫡
ありがとうございます！

**Comment by shinGangan** [comment]
@neginasu 

よろしくお願いします〜！

**Comment by neginasu** [comment]
@shinGangan 

遅くなって申し訳ないです🙇‍♀️

記事の作成が完了しましたので、ご確認とレビューよろしくお願いいたします！

https://zenn.dev/comm_vue_nuxt/articles/8ec289200a9b2d

**Comment by shinGangan** [comment]
@neginasu 

遅くないですよ！忙しい中執筆してくれてありがとうございます～🙏

後程レビューします！

**Comment by neginasu** [comment]
@shinGangan 
ありがとうございます！
よろしくお願いします🙇‍♀️

**Comment by shinGangan** [comment]
@neginasu 

お疲れ様です〜！特に問題ないかと思います🙆
強いてあげるとすると以下の1点です。

#### (所感) 懇親会の様子は1つのセクションにしても良さそう

まとめで「コミュニティの雰囲気」を特に推して伝えていると思います。
そのため、懇親会で話して気になったことや「xxさんとyyについての話をして今後の行動の参考になった」など、コミュニティらしさのある話があると書いてみても良いのかなと感じました。

本件はあくまで所感ですので優先度低めです！
お手隙の際に公開してもらって大丈夫です〜🙆

**Comment by neginasu** [comment]
@shinGangan 
レビューありがとうございます！

沢山の方とお話ししたため、どの方と何の話をしたかがあやふやになってしまい...💦今回はこのまま公開しました🙇‍♀️

コミュニティらしさのある話については次回記事を書くときに一つのセクションにしてかけるように当日にメモとっておきます...!

**Comment by shinGangan** [comment]
@neginasu 

諸々承知です！回答くださりありがとうございます ☺️
優先度は高くないのでもし「書きたい...！」ってなった際には是非是非書いてくださいね。

> コミュニティらしさのある話については次回記事を書くときに一つのセクションにしてかけるように当日にメモとっておきます...!

**Comment by shinGangan** [comment]
記事が無事に公開！LGTMです🎉

https://zenn.dev/comm_vue_nuxt/articles/8ec289200a9b2d
