### ISSUE TITLE
2024年のアドカレ参加表明を募集中 [~2024/12/25]

### ISSUE THREAD

**Issue by shinGangan** [chibivue-land/articles-zenn-plaza#87]
### Context

2024年もアドベントカレンダーの季節がやってきました🎄
今年もVue.js および Nuxtのカレンダーが存在しています。

- Vue.js 2024 : https://qiita.com/advent-calendar/2024/vue
- Nuxt 2024 : https://qiita.com/advent-calendar/2024/nuxt-and-unjs

@shinGangan は「せっかくならPublicationに紐づけて投稿しコミュニティを盛り上げてほしい」と考えています。
「Publicationに紐づけて記事書きます！」という方は是非参加表明して頂けると嬉しいです🙌

なるべく被らずに毎日Vue.js / Nuxtの記事が上がると楽しそうですね (もちろん強制ではないので投稿できる日に是非投稿してください)

**Comment by shinGangan** [comment]
### 予定

- Nuxt の記事は **12/11** 公開で頑張ります
  - https://qiita.com/advent-calendar/2024/nuxt-and-unjs
- Vue.jsの記事は **12/18** 公開で頑張ります
  - https://qiita.com/advent-calendar/2024/vue

**Comment by NaokiHaba** [comment]
Publicationに紐づけて記事書きます！

- Vue.jsの記事は 12/14 公開で頑張ります
  - https://qiita.com/advent-calendar/2024/vue
- Nuxt の記事は 12/18 公開で頑張ります
  - https://qiita.com/advent-calendar/2024/nuxt-and-unjs

**Comment by hiroko-ino** [comment]
毎年誕生日にアドカレ書くと決めているので15日に
Vue.js 2024 : https://qiita.com/advent-calendar/2024/vue
に上げます！

**Comment by neginasu** [comment]
[Vue.js 2024](https://qiita.com/advent-calendar/2024/vue)にVueを勉強していて詰まったところについて23日に上げる予定です！🎄
頑張ります🙌

**Comment by hashibadaiki** [comment]
アドカレ初参戦ですが書きたい記事あったので書きます!
12/24 予定

Vue.js 2024 : https://qiita.com/advent-calendar/2024/vue

**Comment by konkarin** [comment]
12/20に「Nuxt(Vite)でページ遷移時に強制リロードされる事象に立ち向かう」について書きます
https://qiita.com/advent-calendar/2024/nuxt-and-unjs

**Comment by yamanoku** [comment]
12/9にそれぞれで「Vue.jsと周辺エコシステムから振り返る2024年」「Nuxt/UnJSと周辺エコシステムから振り返る2024年」という内容を書こうと思っております🎄

- https://qiita.com/advent-calendar/2024/vue
- https://qiita.com/advent-calendar/2024/nuxt-and-unjs

**Comment by naitokosuke** [comment]
12/4(水)「Vite + Vue + UnoCSS で簡単なグリッドレイアウトの実装」
12/19(木)「Alexander さんの Evan You さんインタビュー動画 about VoidZero について何か書きます」

でやらせていただきます。

**Comment by Gaakuu** [comment]
12/21(土)に、Nuxtのアドベントカレンダーに投稿します！
Nuxtのfetch系APIの比較をする予定です。

**Comment by Skmt3P** [comment]
大変遅くなってしまい、申し訳ございません。初日の記事を公開しましたー！

[Webフロントエンドの面倒な開発環境構築は、なんちゃってモジュラーモノリスで簡略化しよう！](https://zenn.dev/skmt3p/articles/f96ef9f7aa5a3a)

**Comment by shinGangan** [comment]
@kosuke222naito 

LGTMです🎉

https://zenn.dev/comm_vue_nuxt/articles/vite_vue_unocss_setup

**Comment by shinGangan** [comment]
12/04(水) Nuxtカレンダーが空いていたので書きました〜🙌

https://zenn.dev/comm_vue_nuxt/articles/nuxt-composables-nested-auto-imports

**Comment by ryoAccount** [comment]
12/22(日) Nuxtのアドベントカレンダーに投稿する予定です。
nuxt/icon について書きます。

**Comment by shinGangan** [comment]
12/18(水)のVue.jsカレンダーの記事です🎉

https://zenn.dev/comm_vue_nuxt/articles/vue-i18n-custom-block

**Comment by konkarin** [comment]
12/20分のNuxtの記事書きました🥳
https://zenn.dev/comm_vue_nuxt/articles/6f4da63b50a423

**Comment by shinGangan** [comment]
@neginasu 

Vue.js 23日目。LGTMです〜🎉

https://zenn.dev/comm_vue_nuxt/articles/2508e78ffb5e02

**Comment by shinGangan** [comment]
@Gaakuu 

Nuxt 21日目。LGTMです〜🎉

https://qiita.com/Gaakuu/items/e9a7ba563e6ef91bec8e

**Comment by shinGangan** [comment]
たくさんの投稿ありがとうございました🙌
本イシューにリンクがない記事は後ほど拾っていきます！

アドカレ終了のため本イシューはクローズする
